spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb?currentSchema=project_demo
    username: user
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: project_demo
    default-schema: project_demo

server:
  port: 8080

email:
  sender: demo.project@example.com